version: '3'

services:
  app:
    build: .
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: